### PR TITLE
large thumbs format

### PR DESCRIPTION
**Pull request by lucasnz**
Moves large thumbs preview above text. Replaces br with span to provide the best formating for both large and small thumbs

### CODE REVIEW

**Comment by lucasnz** [comment]
Do still look at these minor tweaks please. I think they help with the large thumb layout...

**Comment by pliablepixels** [comment]
date/time icons swapped. will look at the `<br/>` replacement

**Comment by pliablepixels** [comment]
I'm not going to merge the first change yet. Let's look at it later. Right now, if I scale the window width down on my browser, the image gets cut off. On master, it scales to size so that it always shows (of course, leading to more whitespace at the bottom). I currently prefer the latter behavior

**Comment by lucasnz** [comment]
I'll keep working on tweaking. Is that Safari? Seems to look fine in FF or Chrome for me. I wonder if it relates to the pixel scaling problem we found. As it looks like the image is way to big. I'm interested in what you see with the latest couple of commits.

**Comment by pliablepixels** [comment]
No, this is Chrome on mac - using the usual make_desktop.sh

**Comment by lucasnz** [comment]
I'd like to know how things look with the latest commit. If it looks fine, I'll work on tidy up; navtitle, windows resize/rotate and a couple references to $scope.rowHeight...

**Comment by pliablepixels** [comment]
Haven't looked a the code yet but quick feedback:

a) Compared to master - seems to be doing a better job at whitespace below
b) Compared to master - the image is not scaling up when where is more space in landscape, at least on iOS. Example, I used small thumbs - saw the list. Rotated, the thumbs stayed exactly the same size while in master they scale more as they get more space.

Seems like a win some lose some situation that comes down to preferences so far!

**Comment by lucasnz** [comment]
Yes, I noted in my previous comment that resize/rotate is still an issue. How does it look if you refresh the page in landscape mode? If it looks ok, then it will be worth making the resize code work properly...

**Comment by pliablepixels** [comment]
Refresh in landscape mode works as expected. Is that is problem spot?

**Comment by lucasnz** [comment]
So, the layout is ok, after a refresh? I think I know how to fix this...

**Comment by pliablepixels** [comment]
I’m probably misunderstanding your ask. Layout is same as before. Refresh doesn’t affect anything.

**Comment by lucasnz** [comment]
Re-reading your comments, it seems you want the small thumbs larger in landscape. That's super easy to adjust! I'd be interested in seeing screenshots of the two comparisons your were talking about - that would help me get the small thumbs right (or the same as existing) while reducing whitespace and improving the large thumbs :)

**Comment by lucasnz** [comment]
In terms of adjusting the sizes, I feel like we don't need a difference between landscape and not. It's straight forward to tweak, just a matter of adjusting the below numbers, this is what I have right now - means the small thumbs are able to be a bit bigger;

@@ -3357,28 +3357,28 @@ angular.module('zmApp.controllers')
       var ld = NVR.getLogin();
       var landscape = ($rootScope.devWidth > $rootScope.devHeight) ? true:false;
       var maxRowHeight;
 
       if (ld.eventViewThumbsSize == 'large') {
-        maxRowHeight = 350;
+        maxRowHeight = 0.7* $rootScope.devHeight;
         if (landscape) {
           // go till 90% of width in large landscape, but restricted to useable row height 
           return calculateAspectRatioFit(mw, mh, 0.9* $rootScope.devWidth, maxRowHeight);
         } else {
                     // go till 80% of width in large portrait, but restricted to useable row height 
 
-          return calculateAspectRatioFit(mw, mh, 0.8* $rootScope.devWidth, maxRowHeight);
+          return calculateAspectRatioFit(mw, mh, 0.9* $rootScope.devWidth, maxRowHeight);
         }
 
       } else { // small
-        maxRowHeight = 70;
+        maxRowHeight = 120;
         if (landscape) {
           // go till 50% of width in small landscape, but restricted to useable row height 
-          return calculateAspectRatioFit(mw, mh, 0.5* $rootScope.devWidth, maxRowHeight);
+          return calculateAspectRatioFit(mw, mh, 0.4* $rootScope.devWidth, maxRowHeight);
         } else {
                     // go till 30% of width in small portrait, but restricted to useable row height 
-          return calculateAspectRatioFit(mw, mh, 0.3* $rootScope.devWidth, maxRowHeight);
+          return calculateAspectRatioFit(mw, mh, 0.4* $rootScope.devWidth, maxRowHeight);
         }
 
       }
      
     }

**Comment by pliablepixels** [comment]
I think I’ve addressed whitespaces in master. Let me know if it works for you too. Tested on desktop and iOS.

**Comment by lucasnz** [comment]
Definitely an improvement, but we need to put the text on a single line (for large thumbs only), the thumb needs to be centered and I think the text looks better below the image. These are all very minor tweaks. I'll create another PR...

**Pull request closed without merging**
