### PR TITLE
Resizing updates

### PR DESCRIPTION
**Pull request by lucasnz**
This PR bases the row height on the image height, so it helps ensure there isn't too much white space...

### CODE REVIEW

**Comment by pliablepixels** [comment]
Quick browser check - it doesn't fix the resizing issue. I still need to scroll to fix it. Is that the intent of this PR?

**Comment by lucasnz** [comment]
Yes, that was one of the goals (I thought I'd succeeded in that one). The other is to set the row heights based on the thumb height. This means rows can be different heights (if camera aspect ratios are different). So I've updated navTitle and scrollbynumber to handle the variation. The benefit of this, is less whitespace. I'll continue to work on the former, it has to be solvable!

**Comment by lucasnz** [comment]
Thinking about this, I was planning on making it scroll anyway. Otherwise when you rotate the phone you end up in a different place... Perhaps hold fire on merging until I've done that (kill two birds with one stone?)

**Comment by lucasnz** [comment]
Try it now. Resizing moves you to a different place in the list, and ideally I'd like to scroll you back to where you were - but aside from this looks to be working correctly now.

**Comment by pliablepixels** [comment]
Are you done with all changes?

**Comment by pliablepixels** [comment]
the flex unset part is not working, but I've found a way to keep the time on the same line as intended. I'll merge this and PR to master. For some reason, I can't push changes to this PR (I may be doing it wrong)

**Comment by lucasnz** [comment]
I think I've solved the issue whereby when you resize (or rotate the phone) it moves you to a different part of the event list. I've been running the code for a couple days. It scrolls you back to where you where you were before the resize... I'll probably raise another PR after you've looked at the minor large thumb PR I raised (if I push the commit it will add it to that open PR) - no particular rush :)

**Pull request merged**
