### PR TITLE
lucky last large thumbs PR

### PR DESCRIPTION
**Pull request by lucasnz**
I'm hopeful this resolves the positioning of the buttons. I still haven't figured out the resize bug (I'll keep working on that). I'd also like to see the row heights controlled by the image height, but this still needs some work...

### CODE REVIEW

**Comment by pliablepixels** [comment]
What is a g-class ?

**Comment by lucasnz** [comment]
Where did i say g class - that is a typo? The last commit I mention the class called 'col'

**Comment by pliablepixels** [comment]
Yup check events.html. You have g-class instead of ng-class in 2 places which means the toggles are not being applied. You may want to fix and test. I’ll test tomorrow.

**Comment by lucasnz** [comment]
Ah - yes. Replaced the br with a span but it didn't work due to the typo.

**Comment by lucasnz** [comment]
I see "<div ng-if="event.Event.Notes" >" is now inside the div with the rest of the info. The problem with this (of small thumbs), is if the notes are long, they need to be word wrapped - which I don't think looks so good. Do you prefer it word wrap or below the small thumb? Either way it need minor tweaking. Let me know, and I'll adjust accordingly.

I think I've solved the resize issue. But lets close off these little adjustments first.

**Comment by lucasnz** [comment]
I'm pretty confident I have resolved the resizing problem, and as a side effect this has enabled me to better size the rows. But before, I commit that code, I want to make sure we have the layout right.

I'm inclined to put the notes below the image in the small thumbs mode (that's what I've done but haven't yet committed), but I think you moved it up into the section to the left of the small thumb (so maybe you'd prefer it word wrapped there?). If you want the latter, then this PR needs to word wrap the notes (they currently get chopped off by the image). But it all hinges on how it looks on Apples devices (aside from the need to word wrap the notes, this PR seems to look ok on Windows and Android for me).

**Comment by pliablepixels** [comment]
I haven’t run the code yet. Just responding to a comment above. I don’t want to do word wrapping anywhere. I’ve converted to truncation in master. Words should not be wrapping on any row.

**Comment by lucasnz** [comment]
Correct, it's not warping at the moment, it's chopping off the note. I wasn't sure if that was intended in the small thumbs view. If it if intended, this PR should be correct.

**Comment by pliablepixels** [comment]
ok testing now (made a mod to master to add ellipsis to truncation of notes)

**Comment by pliablepixels** [comment]
My observations so far (only testing on browser/chrome with width squeezed)

**small thumbs**
I prefer master (70 pixels of white space vs 90 pixels of whitespace).  

PR:
pr1 
MASTER:
master1

** large thumbs **
I'd prefer  event name (with tag icon) to be on a new line (master)
I prefer the thumb centering of PR (will merge manually)

PR:
pr2

Master:
master2

At this stage, I don't think there is anything else left to tweak. I'll apply your center change manually for large, but as far as the rest goes, I'm not seeing a whole lot of difference. (Have tested on iOS too)

**Comment by lucasnz** [comment]
Ok, I prefer the event title on a same line in large thumbs but it's not a biggie. I'll close this PR and submit a new one with the resizing code...

**Pull request closed without merging**
