### PR TITLE
Signed-off-by: Veress Krisztián <krive001@gmail.com>

### PR DESCRIPTION
**Pull request by krive001**
update help-hu.html locale-hu.json

### CODE REVIEW

**Comment by krive001** [comment]
Hello.
I wrote a start line because if you start it, for example: ./checklang.py will indicate a bug who uses a Python version 3.5.

**Comment by pliablepixels** [comment]
ok, in that case I'll remove the python statement as we want this to work with both versions. Users can invoke `python ./checklang.py` or `python3 ./checklang.py` as needed

Question: there is a conflict since I merged your other PR. Please see below. Which is the right one? I'll resolve and merge

```
<<<<<<< 558
    "kEmailNotConfigured"        :"Email cím nincs beállítva",
=======
    "kEmailNotConfigured"        :"Email nincs konfigurálva",
>>>>>>> master
```

**Comment by krive001** [comment]
#559 good

2017-11-10 12:36 GMT+01:00 Pliable Pixels <notifications@github.com>:

**Comment by krive001** [comment]
Good command Line python cheklang.py or python3
No ./


2017. nov. 10. 14:37 ezt írta ("Krisztián Veress" <krive001@gmail.com>):

**Pull request merged**
