### PR TITLE
large thumbs tweaks

### PR DESCRIPTION
**Pull request by lucasnz**
Tweaks based off the latest master... I still think having the row height based off the thumbs height would offer the best layout. But perhaps this gives the best compromise?

### CODE REVIEW

**Comment by pliablepixels** [comment]
Can you do just a PR with the text at the bottom for the large? I'm not sure I want to keep playing with the div/spans/general padding anymore - they always seem to break at some dimension.

This is what I see with 973 when I resize the browser window:

Screen Shot 2020-09-11 at 7 17 04 AM

**Comment by pliablepixels** [comment]
Okay, I've manually applied your text at bottom code for large.

There is still one issue that I don't know how to solve yet (and don't really care as much):
In the electron build (desktop browser) mode, when you scale the browser width around, you'll see the row height look incorrect at some dimensions. A quick scroll fixes it. I think this is because the view does not get refreshed, even if I force a digest loop. Maybe something to do with how collection-repeat works. But the moment I scroll, the rows get to the right size. This only occurs when you keep resizing the window.

I tried removing the list and re-adding it. It leads to flicker as well as that same infinite scroll isNative error.

**Comment by lucasnz** [comment]
Interesting, I'm in bed now, so can't tweak. The buttons being too high, shouldn't be related to changing the br to a span. I think that's to do with the div structure - but I can't check it now...

**Comment by lucasnz** [comment]
Yes, this resize problem, is the same problem I was having when I based the row heights off the image size. I hadn't found a workaround for that yet.

**Comment by lucasnz** [comment]
That weird display at the top (recording in progress) pushing the date into the next line, had been there for ages. I had simply put a br in to push the text into a second line. This seemed to look better. But I don't know if that actually matters. https://github.com/pliablepixels/zmNinja/commit/83d76ae067c476e34fa9659a34b81eeba373849c

**Comment by lucasnz** [comment]
latest master is an improvement. Just need to swap that br for a span and center the large thumb. Once that has happened the large thumb row height needs to be reduced a bit more... We're so close now! I'll try one more PR.

**Pull request closed without merging**
