### PR TITLE
row height wasn't recalculating after changing thumb size

### PR DESCRIPTION
**Pull request by lucasnz**
also simplified scrollTo function (loop no longer required with fixed row heights).

Changes to doRefresh to apply "isChecked" based on monitorFilter actually squashes a number of minor issues around ensuring the monitor filter displays correctly on re-enter the filter screen too.

### CODE REVIEW

**Review by pliablepixels — COMMENTED** [review]
We are returning here with a final value, so it should return a d.resolve(true)

**Comment by lucasnz** [comment]
> 
> 
> We are returning here with a final value, so it should return a d.resolve(true)

I've removed this commit, as it addresses a different issue than the original PR... I'm not 100% sure how this is meant to work, but I was getting a error when there were no events return in getInitialEvents() on these lines:
```
            loadMore()
            .then (function () {
              return d.resolve(true);
            });
```

**Comment by lucasnz** [comment]
Extract from the console output:
Error: loadMore() is undefined
getInitialEvents/<@https://zm.brdbnt.com/js/EventCtrl.js:740:13

**Comment by lucasnz** [comment]
Is this the correct way to resolve the error?
```
@@ -735,14 +735,12 @@ angular.module('zmApp.controllers')
           // if last page has less events
           //console.log("**Loading Next Page ***");
           if (myevents.length < maxEventsToLoad) {
             //console.log ("EVENTS LOADED="+JSON.stringify($scope.events));
             NVR.debug("EventCtrl:loading one more page just in case we don't have enough to display");
-            loadMore()
-            .then (function () {
-              return d.resolve(true);
-            });
+            loadMore();
+            return d.resolve(true);
 
           } else {
             return d.resolve(true);
 
           }

```

**Comment by pliablepixels** [comment]
I was returning promises incorrectly. That undefined issue is fixed.
However we have an unresolved error:

If you go to events, apply a filter (say to a monitor with just a few events) and reset it, then it keeps saying 'no more events' even though there are. I think we are not clearing currentEvents count /pageCount variables

**Comment by lucasnz** [comment]
Yep, that sorted that part. But back to the original intent of the PR (row height wasn't recalculating after changing thumb size). This issue was only occurring when a filter was applied...

**Comment by pliablepixels** [comment]
I'd prefer to just leave isChecked out for rowheight computation. The side effect of this is if you are not including a monitor, it will still be used for rowHeight computation, but that isn't a big deal. I prefer it to adding more case specific code

**Comment by lucasnz** [comment]
That approach seems reasonable. This PR also ensures the monitors are correctly 'checked' on the filter screen after event list reload. Perhaps we move this code into the moniror filter code?

**Comment by pliablepixels** [comment]
how do I replicate the this so I know what you are exactly referring to?

>This PR also ensures the monitors are correctly 'checked' on the filter screen after event list reload. Perhaps we move this code into the moniror filter code?

**Comment by lucasnz** [comment]
I can't test right now, but from memory. Apply a filter with not all the monitors ticked. If you return to the filter screen the monitors are correctly selected (click save). If you refresh the event list (monitors still apply), but on returning to the filter screen, all monitors are ticked.

**Comment by pliablepixels** [comment]
confirmed - applied your patch. Closing this issue out.

**Pull request closed without merging**
