### PR TITLE
Fixed double encoded URLs

### PR DESCRIPTION
**Pull request by fri-K**
Replaced spaces with + signs and removed encodeURI function usage on url

### CODE REVIEW

**Comment by fri-K** [comment]
This is fix for #920

**Comment by pliablepixels** [comment]
@fri-K - did you test the changes in my dev branch? I don't think this url encode is needed

**Comment by fri-K** [comment]
Hi,
oh, sorry I didn't see that you commented on bug thread, I'll check it

**Comment by fri-K** [comment]
As you already have fix for #920, then I think we can close this pull request?

**Comment by pliablepixels** [comment]
Before we close it, did you check if my dev branch is working for you?

**Comment by fri-K** [comment]
Yes I did and I responded in bug thread before writing here :)

**Comment by pliablepixels** [comment]
fixed by https://github.com/pliablepixels/zmNinja/commit/9f04d9130f8a0e499f29a50307475797311bfa7d and https://github.com/pliablepixels/zmNinja/commit/4c38f6d8e470dfe0c6711862dd70c5f5276c707a

**Pull request closed without merging**
