### PR TITLE
Add Chinese (Simplified) translation

### PR DESCRIPTION
**Pull request by outline941**
Chinese support (ﾉ>ω<)ﾉ
Not fully translate yet, but I think it's enough.
As I use zmninja android, there may be a new pr for improvement after you add this to android app and I use for a while.

Something confused:
According to https://www.w3schools.com/tags/ref_language_codes.asp ,the language code of Chinese(Simplified) should be zh-Hans. Not sure if it works.

### CODE REVIEW

**Comment by pliablepixels** [comment]
Thanks for the PR. I believe the code is `zh-CN`for simplified chinese. I'll pull and test and make changes if needed.

**Comment by pliablepixels** [comment]
Thanks. What is the display name I should use for this language option in the menu? Is it `(ﾉ>ω<)ﾉ` ?

**Comment by outline941** [comment]
"简体中文"  (≧▽≦)

**Comment by pliablepixels** [comment]
Thanks. If you want, I can build a desktop version for you to test and see (if so, please let me know which desktop version)

**Comment by outline941** [comment]
Sorry, I have to say that the "(≧▽≦)" is superfluous.
Thanks, I use linux.

**Comment by pliablepixels** [comment]
Ok. Here we go, for testing https://drive.google.com/file/d/1DkFbahVKbpGUcnEsahO66vubrYg2GcxM/view?usp=sharing

If you need to modify anything, please put it in a new PR. Thanks.

**Pull request merged**
