### PR TITLE
initial experiments

### PR DESCRIPTION
**Pull request by pliablepixels**

### CODE REVIEW

**Comment by PartialVolume** [comment]
@pliablepixels compiled this branch and initial tests are on a UMI Fair Android 5.1

I see your still committing to this branch so I won't go too in depth with the tests, but these are my initial findings. If you don't see the same thing I can make a quick screen video.

**Montage**
5 cameras used in the montage and arranged in a single column so that they exceed screen height. Scrolling them about 50% of the way to the bottom the title bar behaves as it should do. Scrolling beyond that the title bar behaves oddly, bouncing back into view when it should do. ( This behaviour was found to exist on all other views ).

**Event Montage**
Screen content does not exceed screen height so not relevant.

**Timeline**
Screen content does not exceed screen height so not relevant.

**Events**
Scrolled through about 50+ events and the title bar disappeared and reappeared as it should do. ie disappeared when scrolling contents up and reappeared when scrolling down. No problem here.

**Monitors**
Scroll and title behave as they should do. When you get right to the bottom maybe the title bar pops up too soon when you've not quite reached the bottom but close.

**System Status**
N/A

**Settings**
Scrolls but title bar doesn't disappear

**Dev Settings**
Scrolls and title bar disappears & reappears depending on direction of scroll until you get just over half way then title bar behaviour changes ie keeps popping back down.

**Help**
As per dev settings

**Logs**
As per dev settings, except you only get about 10% down logs when title bar behaviour changes.

Nick

**Comment by PartialVolume** [comment]
@pliablepixels That's strange, I made the scroll lock changes to this branch and then retested everything I  listed above and the shrinking headers all work perfectly now ! Coincidence ?

Could setting a height (95%) for side menu have fixed the odd behaviour of the title bar as you scrolled down on a long list or is it just a coincidence. ?? I wouldn't have thought so but ..

**Comment by PartialVolume** [comment]
@pliablepixels Loaded this branch + my scroll fix onto Android V6. I can confirm that there don't appear to be any adverse affects to the side menu. Tests so far look good on both Android V6 & V5.1. Side menu behaves as it should and no lockups have occurred. I may experiment a little further as I don't think I need the `direction="xy"` in `<ion-scroll zooming="true" direction="xy" style="height:95%">` could be simply `direction="y"` or even left out completely as according to the Ionic info it defaults to y.

Re The squeezing headers. The issues I described [above](https://github.com/pliablepixels/zmNinja/pull/340#issuecomment-250999723) also occur on Android V6.

Where I noted in this [comment](https://github.com/pliablepixels/zmNinja/pull/340#issuecomment-251011481) that the squeezing headers were now behaving correctly. This seems to be intermittent as on the same phone without any changes the headers are not functioning as they should do.

**Comment by pliablepixels** [comment]
@PartialVolume - lets just focus on the scroll getting locked for now. I'll post to the other issue thread.

**Comment by pliablepixels** [comment]
I just made a commit to the shrink header - please update and see if it improves the header re-appearing issue

**Pull request merged**
